In [3]:
import pandas as pd
import os

In [4]:
os.path.exists(r'C:\Users\hp\OneDrive\Desktop\MY\MachineTranslation\hindi.txt')

False

In [5]:
with open(r'C:\Users\hp\OneDrive\Desktop\MY\MachineTranslation\hin.txt', 'r') as f:
    lines = f.readlines()

In [6]:
lines[:5]

['Help!\tबचाओ!\n',
 'Jump.\tउछलो.\n',
 'Jump.\tकूदो.\n',
 'Jump.\tछलांग.\n',
 'Hello!\tनमस्ते।\n']

In [7]:
english_lines = []
hindi_lines = []
for line in lines:
    eng, hin = line.strip().split('\t')
    english_lines.append(eng)
    hindi_lines.append(hin)
    


In [8]:
english_lines[:5]

['Help!', 'Jump.', 'Jump.', 'Jump.', 'Hello!']

In [9]:
hindi_lines[:5]

['बचाओ!', 'उछलो.', 'कूदो.', 'छलांग.', 'नमस्ते।']

In [10]:
data=pd.DataFrame({'English':english_lines,'Hindi':hindi_lines})

In [11]:
data.head()

English    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [12]:
data.shape

(2869, 2)

In [13]:
import keras
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [14]:

tokenizer_eng = Tokenizer()
tokenizer_hin = Tokenizer() 
tokenizer_eng.fit_on_texts(english_lines)
tokenizer_hin.fit_on_texts(hindi_lines) 

In [15]:
tokenizer_eng.word_index

{'the': 1,
 'i': 2,
 'to': 3,
 'you': 4,
 'is': 5,
 'a': 6,
 'he': 7,
 'of': 8,
 'in': 9,
 'my': 10,
 'it': 11,
 'have': 12,
 'this': 13,
 'me': 14,
 'she': 15,
 'for': 16,
 'was': 17,
 'are': 18,
 'do': 19,
 'that': 20,
 'his': 21,
 'your': 22,
 'will': 23,
 'we': 24,
 'what': 25,
 'on': 26,
 'him': 27,
 "don't": 28,
 'at': 29,
 'not': 30,
 'her': 31,
 'like': 32,
 'go': 33,
 'with': 34,
 'be': 35,
 'how': 36,
 'and': 37,
 "i'm": 38,
 'can': 39,
 'time': 40,
 'there': 41,
 'has': 42,
 'know': 43,
 'all': 44,
 'up': 45,
 'they': 46,
 'come': 47,
 'as': 48,
 'very': 49,
 'had': 50,
 'from': 51,
 "it's": 52,
 'please': 53,
 'did': 54,
 'by': 55,
 'when': 56,
 'want': 57,
 'am': 58,
 'here': 59,
 'out': 60,
 'an': 61,
 'going': 62,
 'been': 63,
 'get': 64,
 'take': 65,
 'about': 66,
 'no': 67,
 'father': 68,
 "can't": 69,
 'book': 70,
 'if': 71,
 'india': 72,
 'were': 73,
 'one': 74,
 'tom': 75,
 'money': 76,
 'english': 77,
 'two': 78,
 'tomorrow': 79,
 'would': 80,
 "i'll": 81,
 'day': 

In [16]:
tokenizer_hin.word_index

{'है।': 1,
 'में': 2,
 'नहीं': 3,
 'मैं': 4,
 'वह': 5,
 'से': 6,
 'क्या': 7,
 'है': 8,
 'के': 9,
 'मुझे': 10,
 'को': 11,
 'हैं।': 12,
 'की': 13,
 'हो': 14,
 'बहुत': 15,
 'का': 16,
 'हूँ।': 17,
 'उसने': 18,
 'एक': 19,
 'पर': 20,
 'तुम': 21,
 'था।': 22,
 'यह': 23,
 'कर': 24,
 'लिए': 25,
 'मेरे': 26,
 'कि': 27,
 'उसे': 28,
 'और': 29,
 'इस': 30,
 'हैं': 31,
 'मेरी': 32,
 'भी': 33,
 'अपने': 34,
 'मैंने': 35,
 'रहा': 36,
 'ने': 37,
 'पास': 38,
 'तो': 39,
 'करने': 40,
 'कल': 41,
 'ही': 42,
 'हम': 43,
 'अपनी': 44,
 'काम': 45,
 'गया।': 46,
 'उसकी': 47,
 'उसके': 48,
 'कोई': 49,
 'तुम्हें': 50,
 'तुम्हारे': 51,
 'था': 52,
 'उस': 53,
 'मेरा': 54,
 'साथ': 55,
 'घर': 56,
 'करना': 57,
 'सकते': 58,
 'थी।': 59,
 'गया': 60,
 'समय': 61,
 'बात': 62,
 'आप': 63,
 'पता': 64,
 'रही': 65,
 'कुछ': 66,
 'अभी': 67,
 'बजे': 68,
 'यहाँ': 69,
 'उसको': 70,
 'आज': 71,
 'तक': 72,
 'लगता': 73,
 'तुम्हे': 74,
 'चाहिए।': 75,
 'किताब': 76,
 'मुझसे': 77,
 'अच्छा': 78,
 'अपना': 79,
 'दिया।': 80,
 'सकता': 81,
 'मत': 82,
 'पसं

In [17]:
data['English']=data['English'].apply(lambda x: x.lower())
data['Hindi']=data['Hindi'].apply(lambda x: x.lower())  

In [18]:
data.head()

English    Hindi
0   help!    बचाओ!
1   jump.    उछलो.
2   jump.    कूदो.
3   jump.   छलांग.
4  hello!  नमस्ते।

In [19]:
X=tokenizer_eng.texts_to_sequences(data['English'])
y=tokenizer_hin.texts_to_sequences(data['Hindi'])

In [20]:
X[:10]

[[90], [556], [556], [556], [907], [907], [908], [908], [128, 11], [38, 909]]

In [21]:
data['English'].iloc[:10]

0      help!
1      jump.
2      jump.
3      jump.
4     hello!
5     hello!
6    cheers!
7    cheers!
8    got it?
9    i'm ok.
Name: English, dtype: object

In [22]:
y[:10]

[[1466],
 [1467],
 [1468],
 [1469],
 [1470],
 [1471],
 [990, 990],
 [1472],
 [991, 27, 3],
 [4, 167, 17]]

In [23]:
data['Hindi'].iloc[:10]

0            बचाओ!
1            उछलो.
2            कूदो.
3           छलांग.
4          नमस्ते।
5         नमस्कार।
6         वाह-वाह!
7          चियर्स!
8    समझे कि नहीं?
9     मैं ठीक हूँ।
Name: Hindi, dtype: object

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [25]:
lst=[len(seq) for seq in X]

In [26]:
lst

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 4,
 3,
 3,
 3,
 4,
 4,
 2,
 3,
 2,
 4,
 2,
 3,
 2,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 5,
 3,
 3,
 3,
 4,
 3,
 3,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 4,
 3,
 3,
 2,
 4,
 4,
 3,
 4,
 3,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 3,
 2,
 4,
 4,
 4,
 3,
 4,
 1,
 1,
 4,
 4,
 3,
 3,
 4,
 5,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 3,
 4,
 2,
 3,
 3,
 3,
 4,
 4,
 4,
 3,
 3,
 4,
 3,
 3,
 4,
 3,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 4,


In [27]:
max_len_eng = max(len(seq) for seq in X)

In [28]:
max_len_eng

22

In [29]:
max_len_hin = max(len(seq) for seq in y)

In [30]:
max_len_hin

25

In [31]:
max_len_hin = 25
max_len_eng = 25

In [32]:
X_padded = pad_sequences(X, maxlen=max_len_eng, padding='post')
y_padded = pad_sequences(y, maxlen=max_len_hin, padding='post')

In [33]:
X_padded

array([[ 90,   0,   0, ...,   0,   0,   0],
       [556,   0,   0, ...,   0,   0,   0],
       [556,   0,   0, ...,   0,   0,   0],
       ...,
       [ 71,  10, 337, ...,   0,   0,   0],
       [ 56,   2,  17, ...,   0,   0,   0],
       [ 92,   6,  98, ...,   0,   0,   0]], shape=(2869, 25), dtype=int32)

In [34]:
y_padded

array([[1466,    0,    0, ...,    0,    0,    0],
       [1467,    0,    0, ...,    0,    0,    0],
       [1468,    0,    0, ...,    0,    0,    0],
       ...,
       [ 133,   54, 1349, ...,    0,    0,    0],
       [ 129,    4,  529, ...,    3,   24,  160],
       [  63, 3007,  713, ...,   91,  191, 3011]],
      shape=(2869, 25), dtype=int32)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, TimeDistributed, Dropout

In [36]:
english_vocab_size = len(tokenizer_eng.word_index) + 1
hindi_vocab_size = len(tokenizer_hin.word_index) + 1

In [37]:
hindi_vocab_size

3012

In [42]:
model=Sequential(
    [
    Embedding(input_dim=english_vocab_size, output_dim=128, input_length=max_len_eng),
    Bidirectional(LSTM(256, return_sequences=True)),
    TimeDistributed(Dense(1024, activation='leaky_relu')),
    Dropout(0.5),
    TimeDistributed(Dense(hindi_vocab_size, activation='softmax'))

])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [43]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=5, restore_best_weights=True)

In [44]:
history=model.fit(X_padded, y_padded, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 23s 267ms/step - accuracy: 0.7465 - loss: 2.1881 - val_accuracy: 0.6031 - val_loss: 2.9849
Epoch 2/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 19s 266ms/step - accuracy: 0.7621 - loss: 1.6057 - val_accuracy: 0.6061 - val_loss: 2.9452
Epoch 3/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 19s 267ms/step - accuracy: 0.7634 - loss: 1.5537 - val_accuracy: 0.6060 - val_loss: 2.9023
Epoch 4/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 19s 270ms/step - accuracy: 0.7641 - loss: 1.5223 - val_accuracy: 0.6022 - val_loss: 2.9154
Epoch 5/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 19s 268ms/step - accuracy: 0.7645 - loss: 1.4917 - val_accuracy: 0.5976 - val_loss: 2.9547
Epoch 6/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 20s 272ms/step - accuracy: 0.7664 - loss: 1.4614 - val_accuracy: 0.6017 - val_loss: 3.0392
Epoch 7/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 20s 282ms/step - accuracy: 0.7663 - loss: 1.4322 - val_accuracy: 0.5981 - val_loss: 3.0329
Epoch 8/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 20s 273ms/step - accuracy: 0.7682 - loss: 1.4000 - 

In [45]:
X_padded[:1]

array([[90,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [46]:
hindi_vocab_size

3012

In [47]:
predictions=model.predict(X_padded[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 483ms/step


In [48]:
import numpy as np

In [49]:
hindi_lines[:1]

['बचाओ!']

In [50]:
input_sentence= "Where are you?"
input_sentence= tokenizer_eng.texts_to_sequences([input_sentence])
input_sentence=pad_sequences(input_sentence, maxlen=max_len_eng, padding='post')
predictions=model.predict(input_sentence)
for prediction in predictions:
    predicted_index=np.argmax(prediction, axis=-1)
    predicted_sentence=' '.join([tokenizer_hin.index_word.get(idx, '') for idx in predicted_index if idx!=0])
    print(predicted_sentence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
आप कहाँ है
